services:
  db:
    image: postgres:latest
    restart: unless-stopped # sempre reinia automaticamente
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT:-5050}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local # com driver local os arquicos do file system do docker são clonados para o local, poderia ser para o S3 por exemplo
  pgadmin:
    driver: local
