services:
  db:
    image: postgres:latest
    restart: unless-stopped # sempre reinia automaticamente
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local # com driver local os arquicos do file system do docker são clonados para o local, poderia ser para o S3 por exemplo
